packages:
  - apps/*
  - server/*

catalog:
  '@apollo/client': ^4.0.11
  '@asteasolutions/zod-to-openapi': 8.2.0
  '@biomejs/biome': 2.3.2
  '@fastify/autoload': ^6.0.0
  '@fastify/cookie': ^11.0.2
  '@fastify/cors': 10.1.0
  '@fastify/helmet': ^12.0.0
  '@fastify/jwt': ^9.0.2
  '@fastify/mongodb': ^8.0.0
  '@fastify/oauth2': ^8.1.2
  '@fastify/rate-limit': ^10.2.0
  '@fastify/sensible': 6.0.3
  '@graphile/depth-limit': ^0.3.1
  '@prisma/client': ^6.1.0
  '@radix-ui/react-accordion': ^1.2.12
  '@radix-ui/react-dialog': 1.1.15
  '@radix-ui/react-dropdown-menu': ^2.1.16
  '@radix-ui/react-scroll-area': ^1.2.10
  '@radix-ui/react-separator': ^1.1.8
  '@radix-ui/react-slot': 1.2.4
  '@radix-ui/react-tooltip': ^1.2.8
  '@radix-ui/themes': ^3.2.1
  '@tailwindcss/postcss': ^4
  '@types/bcrypt': ^6.0.0
  '@types/node': ^20
  '@types/react': ^19
  '@types/react-dom': ^19
  '@vitejs/plugin-react': ^5.1.0
  autoprefixer: ^10.4.23
  axios: ^1.13.4
  babel-plugin-react-compiler: 1.0.0
  bcrypt: ^6.0.0
  c8: ^10.1.2
  class-variance-authority: 0.7.1
  clsx: ^2.1.1
  concurrently: ^9.0.0
  dotenv: 16.6.1
  esbuild: ^0.27.2
  eslint: ^9
  eslint-config-next: 16.1.1
  fastify: ^5.0.0
  fastify-cli: ^7.4.1
  fastify-plugin: ^5.0.0
  fastify-tsconfig: ^3.0.0
  google-auth-library: ^10.5.0
  graphql: ^16.12.0
  graphql-depth-limit: ^1.1.0
  graphql-query-complexity: ^0.12.0
  graphql-request: ^7.3.5
  lucide-react: ^0.562.0
  mercurius: ^15.0.0
  nanoid: ^3.3.7
  next: 16.1.1
  next-themes: ^0.4.6
  nodemon: ^3.1.11
  pino-pretty: ^13.0.0
  pkce-challenge: ^4.1.0
  postcss: ^8.5.6
  prisma: ^6.1.0
  react: 19.2.3
  react-dom: 19.2.3
  react-hot-toast: ^2.6.0
  react-icons: ^5.5.0
  resend: ^3.2.0
  stripe: ^14.14.0
  tailwind-merge: ^3.4.0
  tailwindcss: ^4
  tailwindcss-animate: ^1.0.7
  ts-node: 10.9.2
  ts-node-dev: ^2.0.0
  tsc-alias: ^1.8.10
  tsconfig-paths: 4.2.0
  tsx: ^4.19.2
  tw-animate-css: ^1.4.0
  typescript: ^5
  vite: ^7.2.2
  vitest: ^1.0.0
  yaml: ^2.8.2
  zod: 4.2.1
  zod-to-json-schema: 3.25.1

onlyBuiltDependencies:
  - '@parcel/watcher'
  - '@prisma/client'
  - '@prisma/engines'
  - '@swc/core'
  - bcrypt
  - esbuild
  - prisma
  - sharp
  - unrs-resolver
