packages:
  - apps/*
  - server/*

catalog:
  '@apollo/client': ^4.0.11
  '@asteasolutions/zod-to-openapi': 8.2.0
  '@biomejs/biome': 2.3.13
  '@fastify/autoload': ^6.3.1
  '@fastify/cookie': ^11.0.2
  '@fastify/cors': 10.1.0
  '@fastify/helmet': ^12.0.1
  '@fastify/jwt': ^9.1.0
  '@fastify/mongodb': ^8.0.0
  '@fastify/oauth2': ^8.1.1
  '@fastify/rate-limit': ^10.3.0
  '@fastify/sensible': 6.0.3
  '@graphile/depth-limit': ^0.3.1
  '@jitsi/react-sdk': ^1.4.4
  '@neondatabase/serverless': ^1.0.2
  '@preact-signals/safe-react': ^0.9.0
  '@prisma/adapter-neon': ^6.18.0
  '@prisma/client': ^6.19.2
  '@radix-ui/react-accordion': ^1.2.12
  '@radix-ui/react-dialog': 1.1.15
  '@radix-ui/react-dropdown-menu': ^2.1.16
  '@radix-ui/react-scroll-area': ^1.2.10
  '@radix-ui/react-separator': ^1.1.8
  '@radix-ui/react-slot': 1.2.4
  '@radix-ui/react-tooltip': ^1.2.8
  '@radix-ui/themes': ^3.2.1
  '@tailwindcss/postcss': ^4
  '@types/bcrypt': ^6.0.0
  '@types/jsonwebtoken': 9.0.10
  '@types/node': ^25.1.0
  '@types/react': ^19
  '@types/react-dom': ^19
  '@vitejs/plugin-react': ^5.1.0
  autoprefixer: ^10.4.23
  axios: ^1.13.4
  babel-plugin-react-compiler: 1.0.0
  bcrypt: ^6.0.0
  c8: ^10.1.2
  class-variance-authority: 0.7.1
  clsx: ^2.1.1
  concurrently: ^9.2.1
  dotenv: 17.2.3
  esbuild: ^0.27.2
  eslint: ^9
  eslint-config-next: 16.1.1
  fastify: ^5.7.2
  fastify-cli: ^7.4.1
  fastify-plugin: ^5.1.0
  fastify-tsconfig: ^3.0.0
  google-auth-library: ^10.5.0
  graphql: ^16.12.0
  graphql-depth-limit: ^1.1.0
  graphql-query-complexity: ^0.12.0
  graphql-request: ^7.3.5
  husky: ^9.1.7
  jose: 'catalog:'
  jsonwebtoken: 9.0.3
  lint-staged: ^16.2.5
  lucide-react: ^0.546.0
  mercurius: ^15.0.0
  nanoid: ^3.3.11
  next: ^15.5.7
  next-themes: ^0.4.6
  nodemon: ^3.1.11
  pino-pretty: ^13.1.3
  pkce-challenge: ^4.1.0
  postcss: ^8.5.6
  prisma: ^6.19.2
  react: 19.1.0
  react-dom: 19.1.0
  react-hot-toast: ^2.6.0
  react-icons: ^5.5.0
  react-intersection-observer: ^9.16.0
  react-markdown: ^10.1.0
  react-toastify: ^11.0.5
  rehype-sanitize: ^6.0.0
  rehype-stringify: ^10.0.1
  remark-gfm: ^4.0.1
  remark-parse: ^11.0.0
  remark-rehype: ^11.1.2
  resend: ^6.9.1
  sass-embedded: ^1.93.2
  stripe: ^14.14.0
  tailwind-merge: ^3.4.0
  tailwindcss: ^4
  tailwindcss-animate: ^1.0.7
  ts-node: 10.9.2
  ts-node-dev: ^2.0.0
  tsc-alias: ^1.8.16
  tsconfig-paths: 4.2.0
  tsx: ^4.21.0
  tw-animate-css: ^1.4.0
  typescript: ^5.9.3
  unified: ^11.0.5
  uuid-random: ^1.3.2
  vite: ^7.2.2
  vitest: ^1.6.1
  yaml: ^2.8.2
  zod: 4.2.1
  zod-to-json-schema: 3.25.1

onlyBuiltDependencies:
  - '@parcel/watcher'
  - '@prisma/client'
  - '@prisma/engines'
  - '@swc/core'
  - bcrypt
  - esbuild
  - prisma
  - sharp
  - unrs-resolver
